// Generated by Wrangler by running `wrangler types`

interface Env {
	S3_ENDPOINT: string;
	BUCKET_NAME: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	AWS_REGION: string;
	SRC_S3_ENDPOINT: string;
	SRC_BUCKET_NAME: string;
	SRC_AWS_ACCESS_KEY_ID: string;
	SRC_AWS_SECRET_ACCESS_KEY: string;
	SRC_AWS_REGION: string;
	Q: Queue;
}
